* Transform Chinook data to JSON

This repository contains a Java utility that extracts data from a
[[https://github.com/lerocha/chinook-database][Chinook sample database]] and transform the results to JSON.

The resulting JSON was used to populate [[https://en.wikipedia.org/wiki/Elasticsearch][elasticsearch]] when trying out elasticsearch in 2013/2014.

The Chinook sample database is an Open Source replacement for the
"Northwind" database owned by Microsoft.  The Chinook database lists
music customers and their purchases.

This utility is packaged as a maven project, created with m2e in
eclipse.

** How to use

*** Install elastic

[[https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html][Install elasticsearch using apt on debian]].

**** Generate passwords and tokens
Reset the password of the elastic built-in superuser with
#+begin_example
  /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
#+end_example


Generate an enrollment token for Kibana instances with
#+begin_example
  /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
#+end_example


Generate an enrollment token for Elasticsearch nodes with
#+begin_example
  /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s node
#+end_example
